---
sidebar: sidebar
permalink: objstore-interclusterlifdown-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: objstore.interclusterlifdown events
---

= objstore.interclusterlifdown events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== objstore.interclusterlifDown
*Severity*::
ERROR
*Description*::
This message occurs when the object-store client cannot find an operational LIF to communicate with the object-store server. This node will not allow object-store client traffic until the intercluster LIF is operational.
*Corrective Action*::
Use the "network interface show -role intercluster" command to check intercluster LIF status. Verify that the intercluster LIF is configured correctly and is operational. If an intercluster LIF is not configured, use the "network interface create -role intercluster" command to create it.
*Syslog Message*::
Object-store client could not find an operational intercluster LIF (IPspace ID: %d) on node %s.
*Parameters*::
*ipspaceID* (INT): IPspace ID of the intercluster LIF.
*nodeUuid* (STRING): UUID of the node.
