---
sidebar: sidebar
permalink: sm-xfer-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: sm.xfer events
---

= sm.xfer events
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== sm.xfer.afs.divergence
*Severity*::
NOTICE
*Description*::
This message occurs when active file system diverges on a SnapMirror(R) destination. The active file system version UUID must match the version UUID of the latest Snapshot(tm) copy on the destination volume or the Snapshot copy that is currently being replicated to the destination volume. The system automatically resolves the divergence by performing a SnapRestore(R) operation.
*Corrective Action*::
(None).
*Syslog Message*::
Active file system with version UUID %s has diverged from the latest Snapshot copy %s version UUID %s on destination volume %s.
*Parameters*::
*afs_uuid* (STRING): Version UUID of the active file system. Internal use only.
*snap_name* (STRING): Name of the latest Snapshot copy on the destination volume.
*latest_snap_uuid* (STRING): Version UUID of the latest Snapshot copy on the destination volume. Internal use only.
*dst_path* (STRING): Destination volume of the SnapMirror relationship.

== sm.xfer.fail.del.snap
*Severity*::
ERROR
*Description*::
This message occurs when deletion of a Snapshot(tm) copy on the destination volume fails, and therefore a subsequent transfer exceeds the maximum supported Snapshot copy count for the vault destination.
*Corrective Action*::
Manually delete the Snapshot copies from the destination volume and reissue the failed SnapMirror command.
*Syslog Message*::
Unable to delete Snapshot copy '%s' from destination volume '%s' of the relationship with relationship UUID '%s' to make space for for newer Snapshot copies.
*Parameters*::
*snap_name* (STRING): Snapshot copy that was not deleted.
*dst_path* (STRING): Destination volume of the relationship.
*relationship_id* (STRING): UUID of the snapmirror relationship.

== sm.xfer.fail.maxlim.snap
*Severity*::
ALERT
*Description*::
This message occurs when a SnapMirror(R) transfer fails because the maximum supported Snapshot(tm) copy limit for a SnapMirror destination is reached and there is no space for a new, incoming Snapshot copy.
*Corrective Action*::
Reduce the "keep" count by using the "snapmirror policy modify-rule -policy [policy_name] -keep [keep_count]" command, or by manually deleting Snapshot copies from the SnapMirror(R) destination.
*Syslog Message*::
The number of Snapshot copies on destination volume '%s' of the relationship with relationship UUID '%s' and policy '%s' has reached the maximum supported.
*Parameters*::
*dst_path* (STRING): Destination volume of the relationship.
*relationship_id* (STRING): UUID of the snapmirror relationship.
*policy_name* (STRING): SnapMirror policy name.

== sm.xfer.incr.snap.rename
*Severity*::
ERROR
*Description*::
This message occurs when an incomplete SnapMirror(R) operation is detected for an incremental Snapshot(tm) copy that no longer exists on the SnapMirror(R) source volume. As a result, SnapMirror creates a Snapshot copy with the name "snapmirror_vlt_xfer_recovery" and requires a SnapMirror Resync operation to be performed on the SnapVault relationship to resume data protection.
*Corrective Action*::
Resume data protection either by retaining or deleting the Snapshot(tm) copy. Use the 'snapmirror resync -preserve' to retain it or use the 'snapmirror resync' command to delete it.
*Syslog Message*::
An incomplete SnapMirror operation was detected for an incremental Snapshot copy that no longer exists on the source volume '%s'. The data transfer for the incremental Snapshot copy was completed but the Snapshot copy on the vault destination '%s' was not created. Instead, a Snapshot copy with the name "snapmirror_vlt_xfer_recovery" was created.
*Parameters*::
*src_path* (STRING): Source volume of the relationship.
*dst_path* (STRING): Destination volume of the relationship.

== sm.xfer.no.new.snap
*Severity*::
INFORMATIONAL
*Description*::
This message occurs when a SnapMirror(R) update does not find any new Snapshot(tm) copies to transfer. This can happen when none of the newer Snapshot copies on the source has a SnapMirror(R) label that matches a SnapMirror policy.
*Corrective Action*::
Check that the SnapMirror label from the Snapshot policy matches SnapMirror policy rules.
*Syslog Message*::
SnapMirror update did not find any new Snapshot copies to transfer from the source volume '%s' of the relationship with relationship UUID '%s'.
*Parameters*::
*src_path* (STRING): Source volume of the SnapMirror relationship.
*relationship_id* (STRING): UUID of the snapmirror relationship.

== sm.xfer.warn.limit
*Severity*::
ERROR
*Description*::
This message occurs when a SnapMirror(R) transfer receives a warning when it is approaching the "keep" count of a particular SnapMirror(R) relationship.
*Corrective Action*::
Increase the "keep" count to transfer more Snapshot(tm) copies with the same label using the following command: snapmirror policy modify-rule -policy [policy_name] -keep [keep_count]
*Syslog Message*::
Warnings issued for SnapMirror relationship with source volume '%s' and destination volume '%s' with relationship UUID '%s' : %s
*Parameters*::
*src_path* (STRING): Source volume of the relationship.
*dst_path* (STRING): Destination volume of the relationship.
*relationship_id* (STRING): UUID of the snapmirror relationship.
*warn_str* (STRING): SnapMirror transfer warning.

== sm.xfer.warn.snapshot.count.limit
*Severity*::
ERROR
*Description*::
This message occurs during a SnapMirror(R) transfer, when the Snapshot(tm) count limit is reached for the SnapMirror relationship between the indicated source and destination volumes.
*Corrective Action*::
Delete some Snapshot copies from the destination volume to create space for new Snapshot copies to be transferred to it.
*Syslog Message*::
Snapshot count limit for SnapMirror relationship with source volume '%s' and destination volume '%s' with relationship UUID '%s' has been reached : %s
*Parameters*::
*src_path* (STRING): Source volume of the SnapMirror relationship.
*dst_path* (STRING): Destination volume of the SnapMirror relationship.
*relationship_id* (STRING): UUID of the snapmirror relationship.
*warn_str* (STRING): SnapMirror transfer warning.
