---
sidebar: sidebar
permalink: smbc-avail-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: smbc.avail events
---

= smbc.avail events
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== smbc.avail.aufoDisabled
*Severity*::
ERROR
*Description*::
This message occurs when the primary-bias state is set for the secondary endpoints of the SnapMirror Business Continuity (SMBC) relationships because both of the SMBC clusters lose connectivity to the ONTAP Mediator. It prevents an automatic unplanned failover operation on the secondary endpoints.
*Corrective Action*::
Check the network connection and restore the access to the ONTAP Mediator.
*Syslog Message*::
Primary-bias state is set for the secondary endpoints of the SMBC relationships. ONTAP Mediator IP: "%s", Peer cluster: "%s".
*Parameters*::
*ipAddress* (STRING): ONTAP Mediator IP address.
*peerCluster* (STRING): Peer cluster name.

== smbc.avail.aufoEnabled
*Severity*::
NOTICE
*Description*::
This message occurs when the primary-bias state is cleared for the secondary endpoints of the SnapMirror Business Continuity (SMBC) relationships. It resumes the ONTAP Mediator assisted automatic unplanned failover operation on secondary endpoints.
*Corrective Action*::
(None).
*Syslog Message*::
Primary-bias state is cleared for the secondary endpoints of the SMBC relationships. ONTAP Mediator IP: "%s", Peer cluster: "%s".
*Parameters*::
*ipAddress* (STRING): ONTAP Mediator IP address.
*peerCluster* (STRING): Peer cluster name.

== smbc.avail.primaryBias
*Severity*::
ERROR
*Description*::
This message occurs when the primary-bias state is set for the primary endpoints of the SnapMirror Business Continuity (SMBC) relationships because both of the SMBC clusters lose connectivity to the ONTAP Mediator. It allows primary endpoints to drive the consensus locally without depending on the ONTAP Mediator.
*Corrective Action*::
Check the network connection and restore the access to the ONTAP Mediator.
*Syslog Message*::
Primary-bias state is set for the primary endpoints of the SMBC relationships. ONTAP Mediator IP: "%s", Peer cluster: "%s".
*Parameters*::
*ipAddress* (STRING): ONTAP Mediator IP address.
*peerCluster* (STRING): Peer cluster name.

== smbc.avail.primaryBiasReset
*Severity*::
NOTICE
*Description*::
This message occurs when the primary-bias state is cleared for the primary endpoints of the SnapMirror Business Continuity (SMBC) relationships. It resumes the three-way quorum involving the ONTAP Mediator and peer cluster to derive consensus.
*Corrective Action*::
(None).
*Syslog Message*::
Primary-bias state is cleared for the primary endpoints of the SMBC relationships. ONTAP Mediator IP: "%s", Peer cluster: "%s".
*Parameters*::
*ipAddress* (STRING): ONTAP Mediator IP address.
*peerCluster* (STRING): Peer cluster name.
